# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefas.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tarefas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtarefas.proto\x12\x06tarefa\"K\n\x06Tarefa\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x12\n\nenvolvidos\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"E\n\x0c\x43riarRequest\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x12\n\nenvolvidos\x18\x03 \x01(\t\"O\n\nCriarReply\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x12\n\nenvolvidos\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x0f\n\rListarRequest\".\n\x0bListarReply\x12\x1f\n\x07tarefas\x18\x01 \x03(\x0b\x32\x0e.tarefa.Tarefa\"U\n\x10\x41tualizarRequest\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x12\n\nenvolvidos\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"S\n\x0e\x41tualizarReply\x12\x0e\n\x06titulo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x12\n\nenvolvidos\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\t\"\x1c\n\x0e\x44\x65letarRequest\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x0c\x44\x65letarReply\x12\x10\n\x08\x64\x65letado\x18\x01 \x01(\t2\x98\x02\n\x14gerenciadorDeTarefas\x12\x39\n\x0b\x43riarTarefa\x12\x14.tarefa.CriarRequest\x1a\x12.tarefa.CriarReply\"\x00\x12=\n\rListarTarefas\x12\x15.tarefa.ListarRequest\x1a\x13.tarefa.ListarReply\"\x00\x12\x45\n\x0f\x41tualizarTarefa\x12\x18.tarefa.AtualizarRequest\x1a\x16.tarefa.AtualizarReply\"\x00\x12?\n\rDeletarTarefa\x12\x16.tarefa.DeletarRequest\x1a\x14.tarefa.DeletarReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAREFA']._serialized_start=25
  _globals['_TAREFA']._serialized_end=100
  _globals['_CRIARREQUEST']._serialized_start=102
  _globals['_CRIARREQUEST']._serialized_end=171
  _globals['_CRIARREPLY']._serialized_start=173
  _globals['_CRIARREPLY']._serialized_end=252
  _globals['_LISTARREQUEST']._serialized_start=254
  _globals['_LISTARREQUEST']._serialized_end=269
  _globals['_LISTARREPLY']._serialized_start=271
  _globals['_LISTARREPLY']._serialized_end=317
  _globals['_ATUALIZARREQUEST']._serialized_start=319
  _globals['_ATUALIZARREQUEST']._serialized_end=404
  _globals['_ATUALIZARREPLY']._serialized_start=406
  _globals['_ATUALIZARREPLY']._serialized_end=489
  _globals['_DELETARREQUEST']._serialized_start=491
  _globals['_DELETARREQUEST']._serialized_end=519
  _globals['_DELETARREPLY']._serialized_start=521
  _globals['_DELETARREPLY']._serialized_end=553
  _globals['_GERENCIADORDETAREFAS']._serialized_start=556
  _globals['_GERENCIADORDETAREFAS']._serialized_end=836
# @@protoc_insertion_point(module_scope)
